### ISSUE TITLE
Pages are unstyled in Chrome when fetched over https://

### ISSUE THREAD

**Issue by moreati** [tonysyu/tonysyu.github.com#1]
Feel free to ignore this, it's just a heads up.

I use Chrome with the extension HTTPS Everywhere. This causes your blog (and all github.io pages) to be loaded over http_s_ for me. Since your stylesheets are linked with http Chrome renders only the HTML, and emits warnings to the console e.g.

> Mixed Content: The page at 'https://tonysyu.github.io/readable-regular-expressions-in-python.html' was loaded over HTTPS, but requested an insecure stylesheet 'http://tonysyu.github.io/theme/css/style.css'. This request has been blocked; the content must be served over HTTPS.

I assume you have some static generation tool, but I couldn't identify it.

**Comment by tonysyu** [comment]
Thanks @moreati! I didn't notice this before. I believe I've fixed this issue. Let me know if you still issues.

**Comment by moreati** [comment]
working nicely, ty
